# Generated by Django 4.2.30 on 2026-05-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='members/id_photos/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('group', 'Group / Chama'), ('cooperative', 'Cooperative'), ('farmer', 'Smallholder Farmer'), ('sme', 'Agribusiness SME')], default='individual', max_length=15),
        ),
    ]
