# Generated by Django 4.2.30 on 2026-04-12 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('crop_season', models.CharField(blank=True, help_text='Typical growing/production season e.g. "March–July, October–January"', max_length=100)),
                ('focus_county', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FarmerTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('training_type', models.CharField(choices=[('gap', 'Good Agricultural Practices'), ('post_harvest', 'Post-Harvest Management'), ('financial', 'Financial Literacy'), ('business', 'Business Development'), ('market', 'Market Linkages'), ('cooperative', 'Cooperative Governance')], max_length=15)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=200)),
                ('scheduled_date', models.DateField()),
                ('facilitator', models.CharField(blank=True, max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='trainings_attended', to=settings.AUTH_USER_MODEL)),
                ('value_chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agribusiness.valuechain')),
            ],
            options={
                'verbose_name': 'Farmer Training',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='AgribusinessApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financing_type', models.CharField(choices=[('input', 'Input Financing'), ('seasonal', 'Seasonal Credit'), ('value_chain', 'Value Chain Financing'), ('post_harvest', 'Post-Harvest Handling'), ('equipment', 'Equipment / Irrigation'), ('working_cap', 'Working Capital')], max_length=15)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('farm_size_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('season', models.CharField(help_text='e.g. "Long Rains 2025"', max_length=50)),
                ('purpose', models.TextField(help_text='Describe what the financing will be used for')),
                ('expected_yield', models.TextField(blank=True, help_text='Expected output and revenue')),
                ('market_linkage', models.TextField(blank=True, help_text='Who will you sell to?')),
                ('group_name', models.CharField(blank=True, help_text='If applying as a group', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('staff_notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agri_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_agri_apps', to=settings.AUTH_USER_MODEL)),
                ('value_chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agribusiness.valuechain')),
            ],
            options={
                'verbose_name': 'Agribusiness Application',
                'ordering': ['-applied_at'],
            },
        ),
    ]
