# Generated by Django 4.2.30 on 2026-04-12 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('account_type', models.CharField(choices=[('regular', 'Regular Savings'), ('group', 'Group Savings'), ('social', 'Social Savings')], default='regular', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Annual interest rate %', max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dormant', 'Dormant'), ('closed', 'Closed')], default='active', max_length=10)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Savings Account',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('interest', 'Interest Credit'), ('transfer', 'Transfer')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('internal', 'Internal Transfer')], default='cash', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='savings.savingsaccount')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_savings_txns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Savings Transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FixedDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate %', max_digits=5)),
                ('term_months', models.PositiveIntegerField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('maturity_date', models.DateField()),
                ('interest_earned', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('matured', 'Matured'), ('withdrawn', 'Withdrawn')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fixed Deposit',
                'ordering': ['-start_date'],
            },
        ),
    ]
