# Generated by Django 4.2.30 on 2026-04-12 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_months', models.PositiveIntegerField()),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_repayable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=12)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('disbursement_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('written_off', 'Written Off')], default='active', max_length=15)),
            ],
            options={
                'verbose_name': 'Loan',
                'ordering': ['-disbursement_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('development', 'Development Loan'), ('emergency', 'Emergency Loan'), ('agribusiness', 'Agribusiness Loan'), ('sme', 'SME Loan'), ('group', 'Group / Table Banking Loan'), ('startup', 'Start-Up Loan')], max_length=15)),
                ('description', models.TextField()),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate %', max_digits=5)),
                ('min_term_months', models.PositiveIntegerField(default=1)),
                ('max_term_months', models.PositiveIntegerField(default=36)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=2.0, help_text='Processing fee as % of loan amount', max_digits=5)),
                ('min_savings_months', models.PositiveIntegerField(default=3, help_text='Minimum months of savings history required')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Loan Product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cash', 'Cash')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='loans.loan')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_repayments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Repayment',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('applied_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('applied_term', models.PositiveIntegerField(help_text='Term in months')),
                ('purpose', models.TextField()),
                ('collateral', models.TextField(blank=True, help_text='Describe collateral offered, if any')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.loanproduct')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Application',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='loans.loanapplication'),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
    ]
